### ISSUE TITLE
eslint fails when using webpack aliases

### ISSUE THREAD

**Issue by bigdisk** [chentsulin/electron-react-boilerplate#1321]
For some unknown reason, eslint fails to import the `webpack.config.eslint.js` file and correctly resolve aliases. It's very annoying having tons of linting errors in atom whenever an alias is used. 

Steps to reproduce:
1. Clone the boilerplate
2. Add the following alias into `webpack.config.base.js`:
```
resolve: {
+    alias: {
+      Containers: path.resolve(__dirname, './app/containers/'),
+    },
    extensions: ['.js', '.jsx', '.json'],
    modules: [path.join(__dirname, 'app'), 'node_modules'],
  },
```
![webpack.config.base.js](https://i.imgur.com/oARrrBn.png)
3. Change the import in routes.js to use the alias (as an example):
```
-import HomePage from './containers/HomePage';
-import CounterPage from './containers/CounterPage';
+import HomePage from 'Containers/HomePage';
+import CounterPage from 'Containers/CounterPage';
```
![routes.js](https://i.imgur.com/sXGIDRT.png)

**Results**
* Webpack does resolve the imports correctly, and the app still works with the 2 components displaying properly 👍 
* Yet `npm run lint` throws the following warning (and so does the atom linter):
```
app/routes.js:1:1
  ✖   1:1   Resolve error: Cannot find module /Users/username/projects/electron-react-boilerplate/app/webpack.config.eslint.js  import/no-duplicates
  ✖   1:1   Resolve error: Cannot find module /Users/username/projects/electron-react-boilerplate/app/webpack.config.eslint.js  import/no-named-as-default
  ✖   1:1   Resolve error: Cannot find module /Users/username/projects/electron-react-boilerplate/app/webpack.config.eslint.js  import/no-absolute-path
  ✖   1:1   Resolve error: Cannot find module /Users/username/projects/electron-react-boilerplate/app/webpack.config.eslint.js  import/no-named-as-default-member
  ✖   1:1   Resolve error: Cannot find module /Users/username/projects/electron-react-boilerplate/app/webpack.config.eslint.js  import/extensions
  ✖   1:1   Resolve error: Cannot find module /Users/username/projects/electron-react-boilerplate/app/webpack.config.eslint.js  import/no-unresolved
  ✖   5:22  Missing file extension for "Containers/HomePage"                                                                          import/extensions
  ✖   5:22  Absolute imports should come before relative imports.                                                                     import/first
  ✖   5:22  Unable to resolve path to module Containers/HomePage.                                                                     import/no-unresolved
  ✖   6:25  Missing file extension for "Containers/CounterPage"                                                                       import/extensions
  ✖   6:25  Unable to resolve path to module Containers/CounterPage.                                                                  import/no-unresolved
  ✖   6:25  Absolute imports should come before relative imports.
```

**Comment by bigdisk** [comment]
I've tried every solution listed here to no avail : https://github.com/benmosher/eslint-plugin-import/issues/352

**Comment by uppe-r** [comment]
Hey @bigdisk , is the path for `webpack.config.eslint.js` in the lint logs right? Try [this](https://github.com/benmosher/eslint-plugin-import/issues/352#issuecomment-236821515)

**Comment by bigdisk** [comment]
@uppe-r, I had webpack.config.esling.js there, it didn't work.

I've fixed the issue by creating a new file: `webpack.config.resolve.js` in which I map my resolve/alias:

```javascript
const path = require('path');

/**
 * Determine the array of extensions that should be used to resolve modules.
 */
module.exports = {
  alias: {
    App: path.resolve(__dirname, 'app/'),
    Actions: path.resolve(__dirname, 'app/actions/'),
    Components: path.resolve(__dirname, './app/components/'),
    Containers: path.resolve(__dirname, './app/containers/'),
    Graphql: path.resolve(__dirname, './app/graphql/'),
    Reducers: path.resolve(__dirname, 'app/reducers/'),
    Utils: path.resolve(__dirname, 'app/utils/'),
    // IMPORTANT : Remember to map every alias to .flowconfig too!
  },
  extensions: ['.js', '.jsx', '.json'],
  modules: [path.join(__dirname, 'app'), 'node_modules'],
};
```

Then I imported `webpack.config.resolve.js` in my `webpack.config.base.js` file, to re-use the module mapping (see **resolve**):

```javascript
import path from 'path';
import webpack from 'webpack';
import { dependencies as externals } from './app/package.json';
import resolve from './webpack.config.resolve';

export default {
  [...]

  output: {
    path: path.join(__dirname, 'app'),
    filename: 'renderer.dev.js',
    // https://github.com/webpack/webpack/issues/1114
    libraryTarget: 'commonjs2',
  },

  /**
   * Determine the array of extensions that should be used to resolve modules.
   */
  resolve,

  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'production'),
    }),

    new webpack.NamedModulesPlugin(),
  ],

  [...]
};
```
Finally, I point to `webpack.config.resolve.js` into `.eslintrc`
```json
{
  [...]
  "settings": {
    "import/resolver": {
      "webpack": {
        "config": "../webpack.config.resolve.js"
      }
    }
  },
}
```

Oh, and also I added the same aliases in the `.flowconfig` file:

```
[options]
esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable
esproposal.export_star_as=enable
module.name_mapper.extension='css' -> '<PROJECT_ROOT>/internals/flow/CSSModule.js.flow'
module.name_mapper.extension='styl' -> '<PROJECT_ROOT>/internals/flow/CSSModule.js.flow'
module.name_mapper.extension='scss' -> '<PROJECT_ROOT>/internals/flow/CSSModule.js.flow'
module.name_mapper.extension='png' -> '<PROJECT_ROOT>/internals/flow/WebpackAsset.js.flow'
module.name_mapper.extension='jpg' -> '<PROJECT_ROOT>/internals/flow/WebpackAsset.js.flow'
module.name_mapper.extension='graphql' -> '<PROJECT_ROOT>/internals/flow/WebpackAsset.js.flow'
suppress_comment=\\(.\\|\n\\)*\\$FlowFixMe
suppress_comment=\\(.\\|\n\\)*\\$FlowIssue
suppress_type=$any
suppress_type=$FlowTODO
module.name_mapper='^App' ->'<PROJECT_ROOT>/app'
module.name_mapper='^Actions' ->'<PROJECT_ROOT>/app/actions'
module.name_mapper='^Components' ->'<PROJECT_ROOT>/app/components'
module.name_mapper='^Containers' ->'<PROJECT_ROOT>/app/containers'
module.name_mapper='^Graphql' ->'<PROJECT_ROOT>/app/graphql'
module.name_mapper='^Reducers' ->'<PROJECT_ROOT>/app/reducers'
module.name_mapper='^Utils' ->'<PROJECT_ROOT>/app/utils'
```

That fixed it for me... I think the issue comes the babel translation performed on `webpack.config.base.js` (via the include in `webpack.config.eslint.js`) silently failing. I couldn't find the exact culprit package, I just have to move on with my project.

**Comment by amilajack** [comment]
@bigdisk did you resolve this?

**Comment by Plorark** [comment]
Also facing this problem. I had to turn `"import/no-unresolved"` off while it's not fixed.

**Comment by outkine** [comment]
I think this has been solved by @Mati365 in #1509.

**Comment by Plorark** [comment]
@outkine I've tried Mati's solution, but it crashed my eslint for some reason:

What I've tried: 
```
settings: {
   'import/resolver': {
      webpack: { config: resolve('../webpack.config.eslint.js'), },
   }
}
```

What I've got:
```
[Info  - 15:37:31] ESLint server is running.
[Info  - 15:37:32] ESLint library loaded from: project\node_modules\eslint\lib\api.js
[Error - 15:37:40] Cannot read config file: project\.eslintrc.js Error: resolve is not defined
```

**Comment by julesmoretti** [comment]
@Plorark can you share your .eslintrc file, please? I want to see if you used .eslintrc.js and how you imported path into it...

I am trying to use `import path from 'path';` right at the top and it is giving me this when I run `npm run lint`:

```
Error: Unexpected identifier
/Users/jmoretti/Git/logitech/ux-vc/QuickerLaunch/QuickerLaunchReactJS_clean/.eslintrc.js:1
(function (exports, require, module, __filename, __dirname) { import path from 'path';
                                                                     ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)

```

**Comment by julesmoretti** [comment]
Found it: `const path = require....`

**Comment by Plorark** [comment]
@julesmoretti Oops, sorry, didn't see your message back then. It happens cause webpack eslint deosn't know ES6 while reading the config files by default, that's why you need to import 'path' the old way, just like you found out.

Sorry again :/
