### ISSUE TITLE
responseCallback is not supported

### ISSUE THREAD

**Issue by AlexFrazer** [chentsulin/electron-react-boilerplate#266]
Getting this error in my console when starting up the application from scratch without having changed anything

**Comment by jhen0409** [comment]
It's from [redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/options/syncOptions.js#L52), also related to https://github.com/electron/electron/issues/6307. We didn't use the options page (it's not supported), so it's no problem. Maybe we should avoid this error.

**Comment by jhen0409** [comment]
It should solved by [redux-devtools-extension@2.3.0](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.3.0).

**Comment by burgerzzz** [comment]
I'm still getting this error after pulling down latest release

**Comment by jhen0409** [comment]
@burgerzzz could you check the extension version on the console? Just run:

```js
require('electron').remote.BrowserWindow.getDevToolsExtensions()['Redux DevTools'].version
```

It should no any errors if extension version >= 2.3.0, because I have write a test to ensure no output logs in [redux-devtools-extension repo](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/test/electron/devpanel.spec.js#L86).

**Comment by burgerzzz** [comment]
Looks like you were correct, in that I have version "2.2.1.1" of redux-devtools. Is there a reason electron-devtools-installer installed that version, or is it installed globally from that package? Guess, I'm not sure how to update redux-devtools to >=2.3.0.

**Comment by jhen0409** [comment]
@burgerzzz try use `UPGRADE_EXTENSION=1 npm run dev` to upgrade extensions (I'll add it to readme), if you're tried and it's still getting old version, it maybe related to https://github.com/GPMDP/electron-devtools-installer/pull/14, please wait new version of devtools-installer, or just run following code on the console and restart app:

```js
require('electron').remote.BrowserWindow.removeDevToolsExtension('Redux DevTools')
```
