### ISSUE TITLE
Hot loading not working?

### ISSUE THREAD

**Issue by t1mmen** [chentsulin/electron-react-boilerplate#30]
First off, thank you so very much for a decent starting point to building a desktop app with React. Much appreciated!

The issue I'm running into is full "page" reloading on changes instead of hot loading. Is this expected behavior, or am I doing something wrong? If this is expected, do you have any plans for implementing hot loading? I'd love to help, if you can point me in the right direction (webpack configuration is something I still haven't gotten the grasp on)

**Comment by haustraliaer** [comment]
See https://github.com/chentsulin/electron-react-boilerplate/issues/10

As far as I can see it's a deeper issue with socket.io etc - although some of those issues referenced seem to have been closed... So perhaps it should be working again soon if all that needs to happen is a dependency update?

Either way I'm watching this issue closely before I take the dive into frontend dev for electron ;)

**Comment by t1mmen** [comment]
Thanks @haustraliaer 

I tried updating to the latest versions:

```
    "webpack": "^1.11.0",
    "webpack-dev-server": "^1.10.1"
```

... but no change. Looks like the issue is fixed in https://github.com/webpack/webpack-dev-server/issues/191, but still isn't published to NPM.

**Comment by chentsulin** [comment]
It's remain some issues with webpack `target: 'atom'` and `socket.io`. : (

Anyway, I will try to workaround on this, maybe use `target: 'web'` and ignore all modules that electron built-in and in node_modules folder.

**Comment by chentsulin** [comment]
Should be fixed in 0.2.9.

We can keep tracing issues between `webpack` and `socket.io` at #10
